version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hatamiarash7"
    reviewers:
      - "hatamiarash7"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hatamiarash7"
    reviewers:
      - "hatamiarash7"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hatamiarash7"
    reviewers:
      - "hatamiarash7"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hatamiarash7"
    reviewers:
      - "hatamiarash7"
