image: docker:19

stages:
  - Deploy image

services:
  - docker:dind

docker build:
  stage: Deploy image
  only:
    - master
  script:
    - version=$(cat version.env)
    - echo $version
    - docker build -t nikasproject/server:stable -t docker.pkg.github.com/nikas-project/server/server:latest .
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push nikasproject/server:stable
    - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push docker.pkg.github.com/nikas-project/server/server:latest
