trigger:
  - master

pool:
  vmImage: "ubuntu-18.04"

variables:
  imageName: "nikasproject/server:stable"

stages:
  - stage: Test
    jobs:
      - job: Dependencies
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get upgrade -y
              sudo apt-get install python3 python3-setuptools python3-virtualenv python3-dev python3-pip openssl sqlite libffi-dev -y
              pip3 install nose wheel
              python3 setup.py install
              python3 setup.py nosetests --with-xunit
            displayName: Test project

  - stage: Build
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              repository: $(imageName)
              command: build
              Dockerfile: Dockerfile
