version: "3.7"

services:
  nikas:
    image: nikasproject/server:1.1.3
    restart: unless-stopped
    container_name: nikas
    environment:
      - GID=1000
      - UID=1000
    volumes:
      - ./docker/config:/config
      - ./docker/db:/db
    networks:
      - nikas
    ports:
      - 8080:8080

networks:
  nikas:
    external: false
    driver: bridge
