version: "3.9"

services:
  nikas:
    image: nikasproject/server:2.0.1
    restart: unless-stopped
    container_name: nikas
    environment:
      - GID=1000
      - UID=1000
    volumes:
      - ./docker/config:/config
      - ./docker/db:/db
    networks:
      - nikas
    ports:
      - 8080:8080

networks:
  nikas:
    external: false
    driver: bridge
