version: "3.9"

services:
  nikas:
    image: nikasproject/server:2.0.4
    restart: unless-stopped
    container_name: nikas
    environment:
      - GID=1000
      - UID=1000
    volumes:
      - ./docker/config:/config
      - ./docker/db:/db
    networks:
      - nikas
    ports:
      - 8080:8080
    healthcheck:
      test: wget --no-cache --no-verbose --tries=1 --spider localhost:8080/admin || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s

networks:
  nikas:
    external: false
    driver: bridge
