name: Deploy

on:
  workflow_run:
    workflows: [ "Tests" ]
    branches: [ master ]
    types: 
      - completed

jobs:
  PyPi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils libsqlite0 libxml2-utils sqlite openssl ca-certificates tini
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Deploy to test server
      run: |
        python setup.py sdist bdist_wheel
        TWINE_PASSWORD=${PYPI_TEST_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
    - name: Deploy
      run: |
        python setup.py sdist bdist_wheel
        TWINE_PASSWORD=${PYPI_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --skip-existing dist/*
