name: Formatter

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Format code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{md,js,html,scss,yaml,yml}
          same_commit: false
          commit_message: "[CI] Format Code!"
          commit_description: "Format code using Prettier"
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Lint Docker files
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: "Dockerfile"
          recursive: true
          verbose: true

      - name: Lint Docker files
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: "Dockerfile.dev"
          recursive: true
          verbose: true
